### ISSUE TITLE
open up access to inner parts

### ISSUE THREAD

**Issue by zvictor** [salmoro/ff-util#12]
Hi @salmoro ! thank you for publishing this handy tool.

I was checking the snippet code published at https://gist.github.com/Drubo/1574291 and I would like to use `ff-util` to achieve similar results. My goal is to transcode a video on-the-fly (`-i pipe:0`), so I need to have access to `ffmpegProcess.stdin`.

I see a few ways to achieve that, but all of them require changing your lib:
- create a `inputStream` in `RunnerProps`
- refactor `run` to return a custom object in which the promise is just one of its atrributes: `run(...).promise`, `run().process`, ...
- still return a promise from `run`, but "attach" the process to it: `promise = run(...); promise.process.stdin`

The best choice depends on how you foresee other parts of the lib growing from here :)

**Comment by salmoro** [comment]
Hi @zvictor 

YW!

Thanks for opening this issue and laying out the options so nicely :)

Ideally I'd prefer the second option as it keeps the function simpler but for consistency sake I'm leaning towards the first option due to the fact that `outputStream` is done that way.

I suspect `outputStream` can't be done differently as by the time the process is returned and gets listened to the process may have already piped out some data. IIRC this is why I had to add it as a function parameter.

BTW the third option is not something I'd go for as IMO it's not intuitive to what you'd expect of a promise.

What do you think?

**Comment by zvictor** [comment]
I agree with you on the points you raised. The problem with the first option is that we will need to write more code to handle the intention of the users (e.g. `spawn(binPath, ['-i', 'pipe:0', ...args], { input: buffer }), which I am not sure will always be the intended action.

**Comment by salmoro** [comment]
Why not something like
```ts
if (inputStream) {
    inputStream.pipe(ffmpegProcess.stdin);
}
```
The user will add the ffmpeg pipe commands (`'-i', 'pipe:0'`) to the args so we don't need to handle it in the code.

**Comment by zvictor** [comment]
yes! that should be enough technically speaking, but we will still have users confused thinking that by setting `inputStream` the lib will take care of the rest.

the decision we need to make is whether we want go with it and maybe just add a note in the README or go beyond and try to make some smart detection (e.g. `if(inputStream  && !args.includes('-i')) args.unshift('-i', 'pipe:0')`)

**Comment by salmoro** [comment]
Right but to make that work we'd either need to make some  assumptions or write extra code to account for all possible scenarios.

Either one of which I'm not a huge fan :)

An example scenario to account for would be if the user wants to pipe in the second input but not the first.

I therefore prefer to keep things simple and we'll just have to add it to the README.

**Comment by zvictor** [comment]
that sounds good to me =)

**Comment by salmoro** [comment]
Would you like to make a PR?

**Comment by zvictor** [comment]
I was hoping to find some time to do it, but it didn't happen yet. Sorry, but I will need to skip it for now.

**Comment by salmoro** [comment]
Nw :)
